trigger:
- master

jobs:
- job: ContractArchitectureAPI
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Enter Container Registry here'
      repository: 'enter-repository-here'
      command: 'buildAndPush'
      Dockerfile: 'Contract.Architecture.Backend/**/Dockerfile'
      tags: '$(Version)'

- job: ContractArchitectureWeb
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'Contract.Architecture.Web'
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build:prod'
      workingDir: 'Contract.Architecture.Web'
  - task: Docker@2
    inputs:
      containerRegistry: 'Enter Container Registry here'
      repository: 'enter-repository-here'
      command: 'buildAndPush'
      Dockerfile: 'Contract.Architecture.Web/**/Dockerfile'
      tags: '$(Version)'