trigger:
- master

jobs:
- job: ContractArchitectureAPI
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: .NET 5.x SDK
    inputs:
      version: 5.x  
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      projects: 'Contract.Architecture.Backend/**/*.csproj'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'custom'
      projects: 'Contract.Architecture.Backend/**/*.csproj'
      custom: 'build'
      arguments: '-p:MSBuildTreatWarningsAsErrors=true --force'
  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: 'Contract.Architecture.Backend/**/*.csproj'
      arguments: '-p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:Exclude="[*Tests]*" -p:CoverletOutput=./coverage-result/'
  - task: reportgenerator@4
    displayName: Consolidate Code Coverage Results
    inputs:
      reports: '$(Build.SourcesDirectory)/**/coverage-result/coverage.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)/coverage-result'
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage Results'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage-result/Cobertura.xml'
      failIfCoverageEmpty: true

- job: ContractArchitectureWeb
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - task: Npm@1
    displayName: npm install
    inputs:
      command: 'install'
      workingDir: 'Contract.Architecture.Web'
  - task: Npm@1
    displayName: npm run lint
    inputs:
      command: 'custom'
      customCommand: 'run lint'
      workingDir: 'Contract.Architecture.Web'
  - task: Npm@1
    displayName: npm run build:prod
    inputs:
      command: 'custom'
      customCommand: 'run build:prod'
      workingDir: 'Contract.Architecture.Web'